# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Execute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run filtering
      run: ./bin/Debug/net6.0/StunTrackersFiltering
    - name: Commit results
      run: |
        git config --global user.name "actions-user"
        git config --global user.email "actions@github.com"
        git add stun-servers.txt
        git add trackers.txt
        git commit -m "Update list"
        git push
